export const styles = {
  zone: {
    margin: "auto",
    alignItems: "center",
    border: `2px dashed #686868`,
    borderRadius: 20,
    display: "flex",
    flexDirection: "column",
    height: "100%",
    justifyContent: "center",
    padding: 20,
    width: "30%",
    cursor: "pointer",
    marginTop: "20px",
  },
  file: {
    background: "linear-gradient(to bottom, #EEE, #DDD)",
    borderRadius: 20,
    display: "flex",
    height: 120,
    width: 120,
    position: "relative",
    zIndex: 10,
    flexDirection: "column",
    justifyContent: "center",
  },
  info: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    paddingLeft: 10,
    paddingRight: 10,
  },
  size: {
    //   backgroundColor: rgba(255, 255, 255, 0.4),
    borderRadius: 3,
    marginBottom: "0.5em",
    justifyContent: "center",
    display: "flex",
  },
  name: {
    //   backgroundColor:rgba(255, 255, 255, 0.4),
    borderRadius: 3,
    fontSize: 12,
    marginBottom: "0.5em",
  },
  progressBar: {
    bottom: 14,
    position: "absolute",
    width: "90%",
    paddingLeft: 10,
    paddingRight: 10,
  },
  hover: {
    borderColor: "#686868",
  },
  default: {
    borderColor: "#CCC",
  },
  remove: {
    height: 23,
    position: "absolute",
    right: 6,
    top: 6,
    width: 23,
  },
  download: {
    margin: "auto",
    color: "white",
    textDecoration: "none",
    border: "1px solid gray",
    padding: "1%",
    backgroundColor: "black",
    borderRadius: "7px",
    fontSize: "20px",
  },
  button2: {
    border: "none",
    borderRadius: "10px",
    padding: "3%",
    fontSize: "20px",
    cursor: "pointer",
  },
};
